Repository LibUsbDotNet/LibUsbDotNet, pull requests merged in 2023-04, with the labels that each got.

#192 Fix the PortNumbers property.
  src/LibUsbDotNet/LibUsb/UsbDevice.Device.cs
Labels: bug

#196 Native libusb version
  .gitignore
  src/LibUsbDotNet/LibUsb/NativeLibraryVersion.cs
Labels: enhancement

#203 Add langId parameter to MonoUsbApi.GetDescriptor
  stage/LibUsbDotNet/MonoLibUsb/MonoLibUsbApiHelpers.cs
  stage/LibUsbDotNet/MonoLibUsb/MonoUsbDevice.cs
Labels: Core

#206 Create build.yaml for v2 branch
  .github/workflows/build.yaml
Labels: Build, CI

#207 Show info example fix
  src/Examples/Show.Info/ShowInfo.cs
  src/LibUsbDotNet/Info/UsbConfigInfo.cs
  src/LibUsbDotNet/Info/UsbDeviceInfo.cs
  src/LibUsbDotNet/Info/UsbEndpointInfo.cs
  src/LibUsbDotNet/Info/UsbInterfaceInfo.cs
Labels: Examples

#165 Adds support for detaching kernel drivers.
  src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
Labels: enhancement

#212 Throw exceptions, fix SupportsDetachKernelDriver.
  src/LibUsbDotNet/Generated/NativeMethods.cs
  src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
Labels: enhancement

#213 Update BenchmarkConsole.cs to fix #108
  stage/BenchmarkCon/BenchmarkConsole.cs
Labels: Examples, v2

#215 vid/pid should be ushort and not short
  stage/LibUsbDotNet/MonoLibUsb/MonoLibUsbApi.cs
  stage/LibUsbDotNet/MonoLibUsb/MonoLibUsbApiHelpers.cs
Labels: v2
